"""permissoes granulares por funcionario

Revision ID: 303001c0b0e6
Revises: ac2a31713310
Create Date: 2026-07-21 14:10:18.883615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303001c0b0e6'
down_revision: Union[str, None] = 'ac2a31713310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissoes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('modulo', sa.Enum('CLIENTES', 'PROCESSOS', 'PRAZOS', 'FINANCEIRO', name='modulo_sistema'), nullable=False),
    sa.Column('pode_visualizar', sa.Boolean(), nullable=False),
    sa.Column('pode_editar', sa.Boolean(), nullable=False),
    sa.Column('pode_excluir', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'modulo', name='uq_permissao_user_modulo')
    )
    op.add_column(
        'users',
        sa.Column('super_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_column('users', 'perfil')
    sa.Enum('ADMIN', 'ADVOGADO', 'ASSISTENTE', name='perfil_usuario').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    perfil_usuario = sa.Enum('ADMIN', 'ADVOGADO', 'ASSISTENTE', name='perfil_usuario')
    perfil_usuario.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column('perfil', perfil_usuario, nullable=False, server_default='ASSISTENTE'),
    )
    op.drop_column('users', 'super_admin')
    op.drop_table('permissoes')
    # ### end Alembic commands ###
