"""schema inicial

Revision ID: ac2a31713310
Revises: 
Create Date: 2026-07-14 17:48:02.846635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2a31713310'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('tipo_pessoa', sa.Enum('FISICA', 'JURIDICA', name='tipo_pessoa'), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('nome_razao_social', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('oab_responsavel', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_table('feriados',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('NACIONAL', 'ESTADUAL', 'MUNICIPAL', name='tipo_feriado'), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'uf', name='uq_feriado_data_uf')
    )
    op.create_index(op.f('ix_feriados_data'), 'feriados', ['data'], unique=False)
    op.create_table('users',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('oab', sa.String(length=20), nullable=True),
    sa.Column('perfil', sa.Enum('ADMIN', 'ADVOGADO', 'ASSISTENTE', name='perfil_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('processos',
    sa.Column('numero_cnj', sa.String(length=25), nullable=False),
    sa.Column('vara', sa.String(length=255), nullable=True),
    sa.Column('tribunal', sa.String(length=50), nullable=True),
    sa.Column('comarca', sa.String(length=255), nullable=True),
    sa.Column('tipo_acao', sa.String(length=255), nullable=True),
    sa.Column('fase_processual', sa.Enum('CONHECIMENTO', 'RECURSAL', 'EXECUCAO', name='fase_processual'), nullable=False),
    sa.Column('polo_ativo', sa.String(length=500), nullable=True),
    sa.Column('polo_passivo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'ARQUIVADO', 'ENCERRADO', name='status_processo'), nullable=False),
    sa.Column('data_distribuicao', sa.Date(), nullable=True),
    sa.Column('valor_causa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ultima_consulta_datajud', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('advogado_responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advogado_responsavel_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_numero_cnj'), 'processos', ['numero_cnj'], unique=True)
    op.create_table('contratos_honorarios',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.Enum('FIXO', 'EXITO', 'MISTO', name='tipo_contrato'), nullable=False),
    sa.Column('valor_contratado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('numero_parcelas', sa.Integer(), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('CUSTAS', 'DILIGENCIA', 'PERICIA', 'OUTROS', name='tipo_despesa'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('origem', sa.Enum('DATAJUD', 'ESCAVADOR', 'MANUAL', name='origem_movimentacao'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas_honorarios',
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PAGO', 'PENDENTE', 'ATRASADO', name='status_parcela'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos_honorarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prazos',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('movimentacao_origem_id', sa.Uuid(), nullable=True),
    sa.Column('data_prazo', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('PEREMPTORIO', 'DILATORIO', 'RECURSAL', name='tipo_prazo'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CUMPRIDO', 'PERDIDO', name='status_prazo'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movimentacao_origem_id'], ['movimentacoes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prazos')
    op.drop_table('parcelas_honorarios')
    op.drop_table('movimentacoes')
    op.drop_table('despesas')
    op.drop_table('contratos_honorarios')
    op.drop_index(op.f('ix_processos_numero_cnj'), table_name='processos')
    op.drop_table('processos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_feriados_data'), table_name='feriados')
    op.drop_table('feriados')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
